#pragma once

#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <cmath>
#include <sstream>
#include <fstream>
#include <memory>
#include <variant>
#include <any>
#include <optional>
#include <functional>
#include <chrono>
#include <thread>
#include <mutex>
#include <filesystem>
#include <utility>
#include <tuple>
#include <typeinfo>
#include <typeindex>
#include <type_traits>
#include <stdexcept>
#include <cassert>
#include <cctype>
#include <climits>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cstdint>
#include <iomanip>
