name: Sardine Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c9a3b356417726715f5c40464f134e # v5.0.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build C++ compiler
        run: cmake --build build

      - name: Run the test suite
        run: |
          python tests/run_tests.py
